##  Question 1
A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units. A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and draw inferences at 5% significance level. Please state the assumptions and tests that you carried out to check validity of the assumptions.

In [29]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm

In [30]:
# Load the dataset
data=pd.read_csv('C:/Users/home/Downloads/Cutlets.csv')
data.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [31]:
unitA=pd.Series(data.iloc[:,0])
unitA[:10]

0    6.8090
1    6.4376
2    6.9157
3    7.3012
4    7.4488
5    7.3871
6    6.8755
7    7.0621
8    6.6840
9    6.8236
Name: Unit A, dtype: float64

In [32]:
unitB=pd.Series(data.iloc[:,1])
unitB[:10]

0    6.7703
1    7.5093
2    6.7300
3    6.7878
4    7.1522
5    6.8110
6    7.2212
7    6.6606
8    7.2402
9    7.0503
Name: Unit B, dtype: float64

In [33]:
# 2-sample 2-tail ttest:   stats.ttest_ind(array1,array2)     # ind -> independent samples
p_value=stats.ttest_ind(unitA,unitB)
p_value

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

In [34]:
p_value[1]     # 2-tail probability

0.4722394724599501

## Question 2
A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports of the laboratories on their preferred list. They collected a random sample and recorded TAT for reports of 4 laboratories. TAT is defined as sample collected to report dispatch. Analyze the data and determine whether there is any difference in average TAT among the different laboratories at 5% significance level.

In [35]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm

In [36]:
data=pd.read_csv('C:/Users/home/Hypothesis Testing/LabTAT.csv')
data.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [37]:
# Anova ftest statistics: stats.f_oneway(column-1,column-2,column-3,column-4)
p_value=stats.f_oneway(data.iloc[:,0],data.iloc[:,1],data.iloc[:,2],data.iloc[:,3])
p_value

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [38]:
p_value[1]

2.1156708949992414e-57

## Question 3

Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.

In [39]:
# H0 == The male-female buyer rations are similar across regions.
# H1 == The male-female buyer rations are not similar across regions.

In [40]:
import pandas as pd
from scipy import stats as stats
import numpy as np

In [41]:
df= pd.read_csv('C:/Users/home/Hypothesis Testing/BuyerRatio.csv')
df.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [42]:
df_table=df.iloc[:,1:6]
df_table

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [43]:
df_table.values

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]], dtype=int64)

In [44]:
val=stats.chi2_contingency(df_table)

In [45]:
val

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [46]:
no_of_rows=len(df_table.iloc[0:2,0])
no_of_columns=len(df_table.iloc[0,0:4])
degree_of_f=(no_of_rows-1)*(no_of_columns-1)
print('Degree of Freedom=',degree_of_f)

Degree of Freedom= 3


In [47]:
Expected_value=val[3]

In [48]:
Expected_value

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [49]:
val[1]

0.6603094907091882

So comparing p value with alpha(0.05),p is greter than alpha so we accept the null Hypothesis,SO `The male-female buyer rations are similar across regions.`

## Question 4

TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain % of the customer order forms. Any error in order form renders it defective and has to be reworked before processing. The manager wants to check whether the defective % varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences

Lets consider:

H0 = That defective forms % does not varies by centre.
H1 = That defective forms % does varies by centre.

In [50]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm

In [51]:
data=pd.read_csv('C:/Users/home/Hypothesis Testing/Costomer+OrderForm.csv')
data.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [52]:
data['Phillippines'].value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [53]:
data['Indonesia'].value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [54]:
data['Malta'].value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [55]:
data['India'].value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [56]:
#Since there are more than 2 variable we will perform Chi-Square test
p_value=stats.chi2_contingency([data['Phillippines'].value_counts(), data['Indonesia'].value_counts(),data['Malta'].value_counts(), data['India'].value_counts()])
p_value

(3.8589606858203545,
 0.2771020991233144,
 3,
 array([[271.75,  28.25],
        [271.75,  28.25],
        [271.75,  28.25],
        [271.75,  28.25]]))

In [57]:
p_value[1]

0.2771020991233144

So comparing p value with alpha(0.05),p is greter than alpha so we accept the null Hypothesis,SO `The defective % does not varies significantly by centres`